/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author andre
 */
public class HomeClients extends javax.swing.JFrame {

    /**
     * Creates new form HomeClients
     */
    public HomeClients() {
        initComponents();
        this.setTitle("Telemedicine - Clients");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new JPanel();
        central = new JPanel();
        userLabel = new JLabel();
        username = new JTextField();
        passwordLabel = new JLabel();
        password = new JPasswordField();
        signInButton = new JButton();
        recoverPasswordLabel = new JLabel();
        registerButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(Color.white);
        setName("Telemnedicine Client"); // NOI18N
        setResizable(false);

        container.setLayout(new BorderLayout());

        userLabel.setText("Username:");

        username.setName("user"); // NOI18N

        passwordLabel.setText("Password:");

        signInButton.setText("Sign in");
        signInButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        recoverPasswordLabel.setText("Forgot your password?");

        registerButton.setText("New Register");
        registerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        GroupLayout centralLayout = new GroupLayout(central);
        central.setLayout(centralLayout);
        centralLayout.setHorizontalGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(centralLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(signInButton)
                    .addComponent(recoverPasswordLabel)
                    .addGroup(centralLayout.createSequentialGroup()
                        .addGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(userLabel))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(username, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, centralLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(30, 30, 30))
        );
        centralLayout.setVerticalGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, centralLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(registerButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(username, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(centralLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(password, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recoverPasswordLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signInButton)
                .addGap(146, 146, 146))
        );

        username.getAccessibleContext().setAccessibleName("username");
        username.getAccessibleContext().setAccessibleDescription("");
        password.getAccessibleContext().setAccessibleName("password");

        container.add(central, BorderLayout.CENTER);

        getContentPane().add(container, BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        String uName = this.username.getText();
        String pWord = this.password.getText();
        
        
    }//GEN-LAST:event_signInButtonActionPerformed

    private void registerButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        this.container.removeAll();
        this.container.repaint();
        
        JPanel registerView = new Register();
        this.container.add(registerView, BorderLayout.CENTER);
        registerView.setVisible(true);
        
        pack();
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel central;
    private JPanel container;
    private JPasswordField password;
    private JLabel passwordLabel;
    private JLabel recoverPasswordLabel;
    private JButton registerButton;
    private JButton signInButton;
    private JLabel userLabel;
    private JTextField username;
    // End of variables declaration//GEN-END:variables
}
