/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import conexion.ClientHandler;
import creation.QuerysInsert;
import java.awt.BorderLayout;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import pojos.Doctor;

/**
 *
 * @author andre
 */
public class AdminMainView extends javax.swing.JPanel {
    
    /**
     * Creates new form AdminMainView
     */
    
    private int doctors;
    private int patients;
    
    public AdminMainView() {
       initComponents();
       this.openSocketButton.setEnabled(false);
       this.userLabel.setVisible(false);
       this.passwordLabel.setVisible(false);
       this.username.setVisible(false);
       this.password.setVisible(false);
       this.buttonRegister.setVisible(false);
       this.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        doctorsLabel = new javax.swing.JLabel();
        patientsLabel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        buttonRegister = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        createDoctorButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        openSocketButton = new javax.swing.JButton();
        closeSocketButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(557, 354));
        setLayout(new java.awt.BorderLayout());

        doctorsLabel.setText("jLabel1");

        patientsLabel.setText("jLabel1");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorsLabel)
                    .addComponent(patientsLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(doctorsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientsLabel)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        add(leftPanel, java.awt.BorderLayout.LINE_START);

        userLabel.setText("User:");

        passwordLabel.setText("Password:");

        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRegister)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLabel)
                            .addComponent(passwordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRegister)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        add(container, java.awt.BorderLayout.CENTER);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        createDoctorButton.setText("Create Doctor");
        createDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDoctorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createDoctorButton)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        add(rightPanel, java.awt.BorderLayout.LINE_END);

        openSocketButton.setText("Open server");

        closeSocketButton.setText("Close server");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(openSocketButton)
                .addGap(41, 41, 41)
                .addComponent(closeSocketButton)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openSocketButton)
                    .addComponent(closeSocketButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void createDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDoctorButtonActionPerformed
       this.userLabel.setVisible(true);
       this.passwordLabel.setVisible(true);
       this.username.setVisible(true);
       this.password.setVisible(true);
       this.buttonRegister.setVisible(true);
    }//GEN-LAST:event_createDoctorButtonActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
        QuerysInsert qi = new QuerysInsert();
        try {
            Doctor doctor = new Doctor();
            doctor.setAddress("aa");
            doctor.setDob(new Date(1,1,1));
            doctor.setName(this.username.getText());
            doctor.setUsername(username.getText());
            doctor.setPhoneNumber(11111);
            doctor.setSalary(0.0);
            doctor.setSpecialty("aa");
            doctor.setSpeciality("aaa");
            doctor.seteMail("aaa");
            doctor.setPassword(this.password.getText());
            
            qi.insertDoctorComplete(doctor);
            qi.insertUserType(this.username.getText(), this.password.getText(),2);
            
            JOptionPane.showMessageDialog(this, "Doctor registered correctly", "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "You have to use a different username", "Error", JOptionPane.ERROR_MESSAGE);
        }
       this.username.setText("");
       this.password.setText("");
       
       this.userLabel.setVisible(false);
       this.passwordLabel.setVisible(false);
       this.username.setVisible(false);
       this.password.setVisible(false);
       this.buttonRegister.setVisible(false);
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void refresh() {
                for(ClientHandler i: ClientHandler.clients) {
            if(i.getDoctor() == null) {
                this.patients++;
            }
            else if(i.getPatient() == null) {
                this.doctors++;
            }
        }
        
        this.patientsLabel.setText("Patients connected " + this.patients );
        this.doctorsLabel.setText("Doctors connected " + this.doctors);
    }
    
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        this.refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton closeSocketButton;
    private javax.swing.JPanel container;
    private javax.swing.JButton createDoctorButton;
    private javax.swing.JLabel doctorsLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton openSocketButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel patientsLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
